### ISSUE TITLE
Failed to install LPMP on Ubuntu 18.04

### ISSUE THREAD

**Issue by cxxszz** [LPMP/LPMP#34]
Hi, when I run the command
`PACKAGES="gm" python3 -m pip install git+https://github.com/AndreaHor/LPMP.git`
I get an error during installing collected packages: lpmp-py. I try to install LPMP on Ubuntu 18.04 with gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~18.04). The full error message is below. Thank you for your time and attention.
`  Cloning https://github.com/AndreaHor/LPMP.git to /tmp/pip-aw_xn3gm-build
Installing collected packages: lpmp-py
  Running setup.py install for lpmp-py ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-aw_xn3gm-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-vi1j_bdf-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/lpmp_py
    copying lpmp_py/raw_solvers.py -> build/lib.linux-x86_64-3.6/lpmp_py
    copying lpmp_py/__init__.py -> build/lib.linux-x86_64-3.6/lpmp_py
    running build_ext
    extension name: graph_matching_py
    Testing gcc...
    ...has version 9.4.0
    Found suitable gcc/g++ version gcc g++
    -- The C compiler identification is GNU 9.4.0
    -- The CXX compiler identification is GNU 9.4.0
    -- Check for working C compiler: /usr/bin/gcc
    -- Check for working C compiler: /usr/bin/gcc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/g++
    -- Check for working CXX compiler: /usr/bin/g++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found OpenMP_C: -fopenmp (found version "4.5")
    -- Found OpenMP_CXX: -fopenmp (found version "4.5")
    -- Found OpenMP: TRUE (found version "4.5")
    -- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
    -- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.0.1") found components:  CXX
    -- /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so/usr/lib/x86_64-linux-gnu/libpthread.so/usr/lib/x86_64-linux-gnu/libsz.so/usr/lib/x86_64-linux-gnu/libz.so/usr/lib/x86_64-linux-gnu/libdl.so/usr/lib/x86_64-linux-gnu/libm.so
    -- /usr/include/hdf5/serial
    --
    -- pybind11 v2.6.2 dev1
    CMake Warning at external/pybind11/tools/pybind11Common.cmake:174 (message):
      USE -DCMAKE_CXX_STANDARD=17 instead of PYBIND11_CPP_STANDARD
    Call Stack (most recent call first):
      external/pybind11/CMakeLists.txt:169 (include)
    
    
    -- Found PythonInterp: /usr/bin/python3 (found version "3.6.9")
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- Found OpenMP_C: -fopenmp (found version "4.5")
    -- Found OpenMP_CXX: -fopenmp (found version "4.5")
    -- Configuring done
    CMake Warning (dev) at src/asymmetric_multiway_cut/CMakeLists.txt:7 (add_library):
      Policy CMP0038 is not set: Targets may not link directly to themselves.
      Run "cmake --help-policy CMP0038" for policy details.  Use the cmake_policy
      command to set the policy and suppress this warning.
    
      Target "asymmetric_multiway_cut_gaec" links to itself.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    CMake Warning (dev) at src/multiway_cut/CMakeLists.txt:7 (add_library):
      Policy CMP0038 is not set: Targets may not link directly to themselves.
      Run "cmake --help-policy CMP0038" for policy details.  Use the cmake_policy
      command to set the policy and suppress this warning.
    
      Target "multiway_cut_gaec" links to itself.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    CMake Warning (dev) at src/asymmetric_multiway_cut/CMakeLists.txt:7 (add_library):
      Policy CMP0038 is not set: Targets may not link directly to themselves.
      Run "cmake --help-policy CMP0038" for policy details.  Use the cmake_policy
      command to set the policy and suppress this warning.
    
      Target "asymmetric_multiway_cut_gaec" links to itself.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    CMake Warning (dev) at src/multiway_cut/CMakeLists.txt:7 (add_library):
      Policy CMP0038 is not set: Targets may not link directly to themselves.
      Run "cmake --help-policy CMP0038" for policy details.  Use the cmake_policy
      command to set the policy and suppress this warning.
    
      Target "multiway_cut_gaec" links to itself.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- Generating done
    -- Build files have been written to: /tmp/pip-aw_xn3gm-build/build/temp.linux-x86_64-3.6
    Scanning dependencies of target lglmain
    Scanning dependencies of target lgl
    [ 25%] Building C object external/DD_ILP/external/lingeling/CMakeFiles/lglmain.dir/lglmain.c.o
    [ 25%] Building C object external/DD_ILP/external/lingeling/CMakeFiles/lgl.dir/lglib.c.o
    [ 25%] Linking C static library liblglmain.a
    [ 25%] Built target lglmain
    [ 25%] Building C object external/DD_ILP/external/lingeling/CMakeFiles/lgl.dir/lglopts.c.o
    [ 50%] Building C object external/DD_ILP/external/lingeling/CMakeFiles/lgl.dir/lgldimacs.c.o
    /tmp/pip-aw_xn3gm-build/external/DD_ILP/external/lingeling/lglib.c: In function ‘lglstampall’:
    /tmp/pip-aw_xn3gm-build/external/DD_ILP/external/lingeling/lglib.c:19233:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
    19233 |  if (rootsonly) noimpls++; goto CONTINUE;
          |  ^~
    /tmp/pip-aw_xn3gm-build/external/DD_ILP/external/lingeling/lglib.c:19233:28: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
    19233 |  if (rootsonly) noimpls++; goto CONTINUE;
          |                            ^~~~
    [ 50%] Building C object external/DD_ILP/external/lingeling/CMakeFiles/lgl.dir/lglbnr.c.o
    [ 50%] Linking C static library liblgl.a
    [ 50%] Built target lgl
    Scanning dependencies of target graph_matching_frank_wolfe
    Scanning dependencies of target MRF_factors
    [ 50%] Building CXX object src/graph_matching/CMakeFiles/graph_matching_frank_wolfe.dir/graph_matching_frank_wolfe.cpp.o
    [ 75%] Building CXX object src/mrf/CMakeFiles/MRF_factors.dir/pairwise_simplex_factor.cpp.o
    g++: fatal error: Killed signal terminated program cc1plus
    compilation terminated.
    src/mrf/CMakeFiles/MRF_factors.dir/build.make:62: recipe for target 'src/mrf/CMakeFiles/MRF_factors.dir/pairwise_simplex_factor.cpp.o' failed
    make[3]: *** [src/mrf/CMakeFiles/MRF_factors.dir/pairwise_simplex_factor.cpp.o] Error 1
    CMakeFiles/Makefile2:1181: recipe for target 'src/mrf/CMakeFiles/MRF_factors.dir/all' failed
    make[2]: *** [src/mrf/CMakeFiles/MRF_factors.dir/all] Error 2
    make[2]: *** Waiting for unfinished jobs....
    g++: fatal error: Killed signal terminated program cc1plus
    compilation terminated.
    src/graph_matching/CMakeFiles/graph_matching_frank_wolfe.dir/build.make:62: recipe for target 'src/graph_matching/CMakeFiles/graph_matching_frank_wolfe.dir/graph_matching_frank_wolfe.cpp.o' failed
    make[3]: *** [src/graph_matching/CMakeFiles/graph_matching_frank_wolfe.dir/graph_matching_frank_wolfe.cpp.o] Error 1
    CMakeFiles/Makefile2:2199: recipe for target 'src/graph_matching/CMakeFiles/graph_matching_frank_wolfe.dir/all' failed
    make[2]: *** [src/graph_matching/CMakeFiles/graph_matching_frank_wolfe.dir/all] Error 2
    CMakeFiles/Makefile2:2294: recipe for target 'src/graph_matching/CMakeFiles/graph_matching_py.dir/rule' failed
    make[1]: *** [src/graph_matching/CMakeFiles/graph_matching_py.dir/rule] Error 2
    Makefile:786: recipe for target 'graph_matching_py' failed
    make: *** [graph_matching_py] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-aw_xn3gm-build/setup.py", line 137, in <module>
        zip_safe=False,
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-aw_xn3gm-build/setup.py", line 35, in run
        self.build_extension(ext)
      File "/tmp/pip-aw_xn3gm-build/setup.py", line 112, in build_extension
        subprocess.check_call(['cmake', '--build', '.', '--target', ext.name] + build_args, cwd=self.build_temp)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'graph_matching_py', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-aw_xn3gm-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-vi1j_bdf-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-aw_xn3gm-build/`

**Comment by cxxszz** [comment]
If I try to install the whole package still on Ubuntu 18.04 via `python3 -m pip install git+https://github.com/lpmp/LPMP.git`, I have the following error
```
Collecting git+https://github.com/lpmp/LPMP.git
  Cloning https://github.com/lpmp/LPMP.git to /tmp/pip-nwibi0ai-build
fatal: remote error: upload-pack: not our ref 36b95962756c1fce8e29b1f8bc45967f30773c00
fatal: The remote end hung up unexpectedly
Fetched in submodule path 'external/Eigen', but it did not contain 36b95962756c1fce8e29b1f8bc45967f30773c00. Direct fetching of that commit failed.
Command "git submodule update --init --recursive -q" failed with error code 1 in /tmp/pip-nwibi0ai-build
```

**Comment by zhangpj** [comment]
> If I try to install the whole package still on Ubuntu 18.04 via `python3 -m pip install git+https://github.com/lpmp/LPMP.git`, I have the following error
> 
> ```
> Collecting git+https://github.com/lpmp/LPMP.git
>   Cloning https://github.com/lpmp/LPMP.git to /tmp/pip-nwibi0ai-build
> fatal: remote error: upload-pack: not our ref 36b95962756c1fce8e29b1f8bc45967f30773c00
> fatal: The remote end hung up unexpectedly
> Fetched in submodule path 'external/Eigen', but it did not contain 36b95962756c1fce8e29b1f8bc45967f30773c00. Direct fetching of that commit failed.
> Command "git submodule update --init --recursive -q" failed with error code 1 in /tmp/pip-nwibi0ai-build
> ```

@cxxszz Hi, Have you solved the problem? I have the same problem when installing LPMP.

**Comment by cjones6** [comment]
Hi, I have Ubuntu 20.04 and the problem for me with building from source seems to have (mainly) been my versions of gcc and g++. After upgrading those as described [here](https://stackoverflow.com/a/66562219), deleting CMakeCache.txt, and rebuilding with cmake I no longer had errors like the one above or "could not load cache".

I hope this helps someone. :slightly_smiling_face: Thanks to the authors for creating this package!

**Comment by AadharshAadhithya** [comment]
Hi, I had the same problem while building LPMP on Ubuntu 20.04 . Some of the sub-modules were missing after initial cloning. I built LPMP after pulling the missing sub-modules, Build was successful then. Hope it helps someone. 

thanks.
